// drawer.js
'use strict';
function initDrawer(){
 const sections=[...document.querySelectorAll('main > section.section')],home=document.getElementById('section-home'),menuBtn=document.getElementById('menuBtn'),back=document.getElementById('appMenuBack'),title=document.getElementById('appMenuTitle'),subtitle=document.getElementById('appMenuSubtitle'),levels=[...document.querySelectorAll('#section-home .app-menu-level')];
 const valid=new Set(['sedantes','antidotos','analgesicos-sistemicos','analgesicos-locales','procedimientos-sedo','proc-no-dolorosos','proc-poco-dolorosos','proc-muy-dolorosos','eventos-adversos','checklist','alta','sueroterapia','hipoglucemia']);
 const groupFor={'procedimientos-sedo':'prep','checklist':'prep','proc-no-dolorosos':'estrategia','proc-poco-dolorosos':'estrategia','proc-muy-dolorosos':'estrategia','sedantes':'calc','antidotos':'calc','analgesicos-sistemicos':'calc','analgesicos-locales':'calc','eventos-adversos':'root','alta':'root'};
 const labels={root:['Menú principal','Selecciona un apartado'],prep:['Preparación Sedación','Selecciona una opción'],estrategia:['Estrategia según procedimiento','Selecciona la intensidad del procedimiento'],calc:['Calculadora','Selecciona un grupo de fármacos']};
 let current='home',level='root';
 const hideAll=()=>sections.forEach(s=>s.hidden=true);
 function showLevel(x='root'){level=labels[x]?x:'root';levels.forEach(p=>p.hidden=p.dataset.menuLevel!==level);title.textContent=labels[level][0];subtitle.textContent=labels[level][1];back.hidden=level==='root';}
 function showHome(x='root',o={}){hideAll();home.hidden=false;current='home';document.body.dataset.view='home';document.body.classList.add('app-menu-open');showLevel(x);scrollTo({top:0,behavior:'smooth'});window.updatePesoDockLayout?.();window.setAppHeaderVar?.();if(o.push!==false)history.pushState({appNav:'menu',level},'',level==='root'?'#menu':`#menu-${level}`);}
 function resetAdverse(){document.querySelectorAll('#section-eventos-adversos [data-adverse-menu],#section-eventos-adversos [data-adverse-detail]').forEach(x=>x.hidden=true);const root=document.querySelector('#section-eventos-adversos [data-adverse-menu="root"]');if(root)root.hidden=false;}
 function setView(view,o={}){if(!valid.has(view))return;const target=document.getElementById(`section-${view}`);if(!target)return;hideAll();target.hidden=false;current=view;document.body.dataset.view=view;document.body.classList.remove('app-menu-open');if(view==='eventos-adversos')resetAdverse();scrollTo({top:0,behavior:'smooth'});window.updatePesoDockLayout?.();window.setAppHeaderVar?.();window.dispatchEvent(new CustomEvent('mainviewchange',{detail:{view}}));if(o.push!==false)history.pushState({appNav:'view',view},'',`#${view}`);}
 function addBacks(){sections.filter(s=>s!==home).forEach(s=>{const view=s.id.replace('section-',''),h=s.querySelector(':scope>.section-header');if(!h||h.querySelector('.section-back-btn'))return;const b=document.createElement('button');b.className='section-back-btn';b.type='button';b.textContent='←';b.setAttribute('aria-label','Volver al menú anterior');b.onclick=()=>showHome(groupFor[view]||'root');h.prepend(b);});}
 home.onclick=e=>{const g=e.target.closest('[data-menu-group]');if(g){showHome(g.dataset.menuGroup);return;}const v=e.target.closest('[data-view]');if(v)setView(v.dataset.view);};back.onclick=()=>showHome('root');menuBtn?.addEventListener('click',e=>{e.preventDefault();showHome('root');});document.querySelectorAll('.tabs [data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));
 const adv=document.getElementById('section-eventos-adversos');adv?.addEventListener('click',e=>{const sub=e.target.closest('[data-adverse-submenu]');const open=e.target.closest('[data-adverse-open]');const root=e.target.closest('[data-adverse-root]');const b=e.target.closest('[data-adverse-back]');if(sub){adv.querySelectorAll('[data-adverse-menu]').forEach(x=>x.hidden=true);adv.querySelector(`[data-adverse-menu="${sub.dataset.adverseSubmenu}"]`).hidden=false;}else if(open){adv.querySelectorAll('[data-adverse-menu],[data-adverse-detail]').forEach(x=>x.hidden=true);adv.querySelector(`[data-adverse-detail="${open.dataset.adverseOpen}"]`).hidden=false;}else if(root){resetAdverse();}else if(b){const d=b.closest('[data-adverse-detail]').dataset.adverseDetail;if(d.startsWith('2.')){adv.querySelectorAll('[data-adverse-menu],[data-adverse-detail]').forEach(x=>x.hidden=true);adv.querySelector('[data-adverse-menu="resp"]').hidden=false;}else resetAdverse();}scrollTo({top:0,behavior:'smooth'});});
 window.addEventListener('popstate',e=>{const s=e.state;s?.appNav==='view'?setView(s.view,{push:false}):showHome(s?.level||'root',{push:false});});addBacks();history.replaceState({appNav:'menu',level:'root'},'','#menu');showHome('root',{push:false});window.setMainView=setView;window.showMainMenu=()=>showHome('root');window.getMainView=()=>current;window.syncDrawerActive=()=>{};
}
